### ISSUE TITLE
Custom method not allowed

### ISSUE THREAD

**Issue by lordprana** [kitsonk/xhr#6]
I'm using the TSDAV package in Deno. https://tsdav.vercel.app/

I use it to interface with the CalDAV protocol.

CalDAV uses certain DAVMethods, in addition to traditional HTTPMethods:

`type DAVMethods = 'COPY' | 'LOCK' | 'MKCOL' | 'MOVE' | 'PROPFIND' | 'PROPPATCH' | 'UNLOCK' | 'REPORT' | 'SEARCH' | 'MKCALENDAR';`

The Deno port of cross-fetch, which this library depends on, uses your xhr library for the web requests. However, your library explicitly restricts non-standard HTTP methods:

`Error: DOMException: The method "PROPFIND" is not allowed.
    at new DOMException (ext:deno_web/01_dom_exception.js:114:19)
    at XMLHttpRequest.open (https://deno.land/x/xhr@0.3.0/mod.ts:525:13)`

Please remove this check, as it is preventing a legitimate use case of your library and is making the Deno environment more difficult for me to use.

Thank you very much.

**Comment by kitsonk** [comment]
I double [checked the standard](https://xhr.spec.whatwg.org/#the-open()-method) and the only thing we should be checking for is forbidden methods.

**Comment by kitsonk** [comment]
This is now available in version 0.3.1.

**Comment by lordprana** [comment]
Wow, I truly appreciate the fast turnaround. I did a little more research for you. I'm not sure if you saw this:

https://www.iana.org/assignments/http-methods/http-methods.xhtml

Here is the list of registered HTTP methods. Could be useful for this library if you want to be a little bit more strict about checking methods.

**Comment by kitsonk** [comment]
I followed the XHR specification exactly on how it handles methods, so that is better in the end.
